const SCREEN_KEYS = {
  HOME_STACK: 'HOME_STACK',
  EXPLORE_STACK: 'EXPLORE_STACK',
  CHAT_STACK: 'CHAT_STACK',
  MY_PET_STACK: 'MYPET_STACK',
  SETTINGS_STACK: 'SETTINGS_STACK',
  MAIN_NAVIGATOR: 'MAIN_NAVIGATOR',
  STACK_NAVIGATOR: 'STACK_NAVIGATOR',
  BOTTOM_NAVIGATOR: 'BOTTOM_NAVIGATOR',
  DRAWER_NAVIGATOR: 'DRAWER_NAVIGATOR',
  EXPLORE: 'EXPLORE',
  HELP: 'HELP',
  HOME: 'HOME',
  LOGIN: 'LOGIN',
  SETTINGS: 'SETTINGS',
  REGISTER: 'REGISTER',
  CHAT: 'CHAT',
  MY_PET: 'MY_PET',
};

export default SCREEN_KEYS;
